# Generated by Django 2.2 on 2020-03-14 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_file_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='private',
            field=models.ManyToManyField(blank=True, null=True, related_name='private_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
